### ISSUE TITLE
No Validation constraints in request object

### ISSUE THREAD

**Issue by gd-estrepetov** [Miheev/java-notes#2]
https://github.com/Miheev/java-notes/blob/c09e31fee519e7b52953dbdaba4568a6c3efb86a/src/main/java/com/boringcompany/notelist/controllers/NoteController.java#L57

@Valid annotation is used on the request object, but there are no validation constraints on it.

Maybe use some of this: https://www.baeldung.com/hibernate-validator-constraints

**Comment by Miheev** [comment]
Fixed
