### ISSUE TITLE
Usage of @Data annotation on Entity class

### ISSUE THREAD

**Issue by gd-estrepetov** [Miheev/java-notes#3]
https://github.com/Miheev/java-notes/blob/c09e31fee519e7b52953dbdaba4568a6c3efb86a/src/main/java/com/boringcompany/notelist/models/Note.java#L17

@Data annotation is not recommended for using with hibernate entities. In your example it is fine but there could be problems with autogenerated hashCode and equals for entities with lazy-loaded fields and @toString.

**Comment by Miheev** [comment]
Fixed
