### ISSUE TITLE
@WebMvcTest can be used

### ISSUE THREAD

**Issue by gd-estrepetov** [Miheev/java-notes#5]
https://github.com/Miheev/java-notes/blob/c09e31fee519e7b52953dbdaba4568a6c3efb86a/src/test/java/com/boringcompany/notelist/controllers/NoteControllerTests.java#L21

@WebMvcTest can be used for testing controller layer in order not to set up all spring-context on each test.

Also, spring assertions can be used for fluent assertions and better error messaging.

Example: https://developer.okta.com/blog/2019/03/28/test-java-spring-boot-junit5

**Comment by Miheev** [comment]
TestRestTemplate used intentionally as business value testing approach and it is able to cover the most of the logic. It seems such class can be used with @SpringBootTest only

https://stackoverflow.com/questions/39213531/spring-boot-test-unable-to-inject-testresttemplate-and-mockmvc

**Comment by Miheev** [comment]
ResponseStatusException is available in last spring boot 2 version
https://www.baeldung.com/spring-response-status-exception
