### ISSUE TITLE
@SpringBootTest is used in wrong place

### ISSUE THREAD

**Issue by gd-estrepetov** [Miheev/java-notes#6]
https://github.com/Miheev/java-notes/blob/c09e31fee519e7b52953dbdaba4568a6c3efb86a/src/test/java/com/boringcompany/notelist/models/NoteTests.java#L11

@SpringBootTest is an integration test and should be used only if spring configuration should be tested (like controllers or custom repository methods). In your case usual JUnit runner can be used (which will faster)

**Comment by Miheev** [comment]
Fixed
