### ISSUE TITLE
Deploying war into servlet container (like tomcat) is a legacy approach.

### ISSUE THREAD

**Issue by gd-estrepetov** [Miheev/java-notes#7]
https://github.com/Miheev/java-notes/blob/c09e31fee519e7b52953dbdaba4568a6c3efb86a/docker/Dockerfile#L6

Deploying war into servlet container (like tomcat) is a legacy approach.

Usually, Spring Boot application is packaged as Jar, which has inside it a servlet container and is executed as any java program (` java -jar note-service.jar`). In this case, you don't need an image with tomcat and java image will be enough.

**Comment by Miheev** [comment]
Fixwd
